In [1]:
import pandas as pd
import json
import os
import deepsig
from IPython.display import display

In [2]:
cols = ['dataset', 'method', 'fitness_rule', 'fitness', 'ACC', 'MCC', 'f1_score', 'avg_odds_diff', 'stat_par_diff', 'eq_opp_diff']

In [3]:
def read_csv_files_from_folder(folder_path):
    dfs = []
    for file_name in os.listdir(folder_path):
        if file_name.endswith(".csv"):
            file_path = os.path.join(folder_path, file_name)
            dfs.append(pd.read_csv(file_path))
    return pd.concat(dfs, ignore_index=True)

mlp_baseline_results = pd.read_csv('simple_mlp_results.csv')
mlp_baseline_results.replace({'simple_mlp_initializer': 'MLP'}, inplace=True)

mlp_xi_reg_results = pd.read_csv('mlp_xi_reg_results.csv')
mlp_xi_reg_results.replace({'mlp_xi_reg_initializer': r'MLP+SDR$_{\xi}$'}, inplace=True)

mlp_results = pd.concat([mlp_baseline_results, mlp_xi_reg_results])

ftl_baseline_results = pd.read_csv('ftl_mlp_results.csv')
ftl_baseline_results.replace({'ftl_mlp_initializer': 'FTL'}, inplace=True)

ftl_xi_reg_results = pd.read_csv('ftl_mlp_xi_reg_results.csv')
ftl_xi_reg_results.replace({'ftl_mlp_xi_reg_initializer': r'FTL+SDR$_{\xi}$'}, inplace=True)

ftl_results = pd.concat([ftl_baseline_results, ftl_xi_reg_results])

# HIFI results are stored as raw per-run CSVs produced by ablation.py's hifi_initializer
hifi_result = pd.read_csv('hifi_results.csv')
hifi_result.replace({'hifi_initializer': 'HIFI'}, inplace=True)

hifi_results = pd.concat([hifi_result, ftl_xi_reg_results])

full_results = pd.concat([mlp_results, ftl_results, hifi_results])

In [4]:
for results in [mlp_results,ftl_results,hifi_results, full_results]:
    results.replace({'adult_dataset_reader': 'Adult Income', 'compas_dataset_reader': 'Compas Recidivism', 'german_dataset_reader': 'German Credit', 'bank_dataset_reader': 'Bank Marketing'}, inplace=True)
    results.rename(columns={'avg_odds_diff': 'Equalized Odds', 'stat_par_diff': 'Statistical Parity', 'eq_opp_diff': 'Equal Opportunity', 'MCC': 'Mathew Correlation', 'ACC': 'Accuracy'}, inplace=True)

In [5]:
fitness_rules_target_metrics = {
    'mcc_parity': {'performance': 'Mathew Correlation', 'fairness': 'Statistical Parity'},
    'mcc_opportunity': {'performance': 'Mathew Correlation', 'fairness': 'Equal Opportunity'},
    'mcc_odds': {'performance': 'Mathew Correlation', 'fairness': 'Equalized Odds'},
    'acc_parity': {'performance': 'Accuracy', 'fairness': 'Statistical Parity'},
    'acc_opportunity': {'performance': 'Accuracy', 'fairness': 'Equal Opportunity'},
    'acc_odds': {'performance': 'Accuracy', 'fairness': 'Equalized Odds'}
}

fitness_rules_target_metrics = {
    'mcc_parity': ('Mathew Correlation', 'Statistical Parity'),
    'mcc_opportunity': ('Mathew Correlation', 'Equal Opportunity'),
    'mcc_odds': ('Mathew Correlation', 'Equalized Odds'),
    'acc_parity': ('Accuracy', 'Statistical Parity'),
    'acc_opportunity': ('Accuracy', 'Equal Opportunity'),
    'acc_odds': ('Accuracy', 'Equalized Odds')
}
fitness_rules_abvr = {
    'mcc_parity': 'Max(MCC - Stat. Parity)',
    'mcc_opportunity': 'Max(MCC - Eq. Odds)',
    'mcc_odds': 'Max(MCC - Eq. Opp.)',
    'acc_parity': 'Max(Acc - Stat. Parity)',
    'acc_opportunity': 'Max(Acc - Eq. Odds)',
    'acc_odds': 'Max(Acc - Eq. Opp.)'
}

for results in [mlp_results,ftl_results,hifi_results,full_results]:
    results['Performance'] = 0
    results['Fairness'] = 0
    results['Fitness Rule'] = ''
    for fitness_rule, (performance_metric, fairness_metric) in fitness_rules_target_metrics.items():
        results.loc[results.fitness_rule == fitness_rule,'Performance'] = results.loc[results.fitness_rule == fitness_rule,performance_metric]
        results.loc[results.fitness_rule == fitness_rule,'Fairness'] = results.loc[results.fitness_rule == fitness_rule,fairness_metric]
        results.loc[results.fitness_rule == fitness_rule,'Fitness Rule Abvr'] = fitness_rules_abvr[fitness_rule]
        results.loc[results.fitness_rule == fitness_rule,'Fitness Rule'] = 'Max(%s - %s)' % fitness_rules_target_metrics[fitness_rule]

/var/folders/z5/rq0dv5jj45qccc_tc39171cm0000gn/T/ipykernel_58323/2887299846.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.58517004 0.58512823 0.5840247  0.5836371  0.57625737 0.5769683
 0.58075151 0.57811729 0.57147862 0.55847176 0.56402881 0.58191431
 0.58343253 0.57740222 0.51579307 0.30958237 0.37962947 0.55899189
 0.53558872 0.2598879  0.57717035 0.50086739 0.33275221 0.37929293
 0.47729109 0.29196869 0.29037704 0.52303609 0.27480633 0.38668781
 0.50626951 0.29960979 0.4042848  0.52119218 0.2936422  0.33522388
 0.49730721 0.25112662 0.35119067 0.510052   0.26843855 0.36081008
 0.52157495 0.30114722 0.42995147 0.48267704 0.29056691 0.23139881
 0.54223416 0.23653437 0.27041017 0.52121263 0.25759348 0.23912165
 0.5223892  0.27406652 0.22303564 0.54094974 0.27699558 0.30939251
 0.51731345 0.30339828 0.37825089 0.52113734 0.26323857 0.33963196
 0.5538225  0.27850228 0.30234984 0.51877126 0.29494101 0.2648939
 0.52742877 0.24492927 0.13407928 0.53530394 0.29087766 0.26820576
 0.55204731 0.29318377 0.14015216 0.51983069 0.3145689  0.47077449
 0.50770986 0.28880123 0.29866465 0.5180664  0.29093567 0.3636368
 0.53289704 0.29737768 0.38084556 0.54328387 0.28002914 0.28232519
 0.53457987 0.27840735 0.33593551 0.51796238 0.25832521 0.35528234
 0.51043886 0.30283203 0.40103589 0.56749877 0.53823804 0.31508219
 0.30011892 0.56841546 0.53593136 0.27736532 0.29276068 0.57486325
 0.55475549 0.37742341 0.41386763 0.58054526 0.52683247 0.30308226
 0.29262695 0.5799324  0.52052204 0.32271689 0.36757294 0.59460839
 0.51334273 0.35016465 0.38279532 0.56696388 0.51290233 0.36145201
 0.31417586 0.58536707 0.52205773 0.35505396 0.34556054 0.56656046
 0.50583602 0.32985378 0.33067725 0.58034596 0.53345208 0.32170125
 0.30777776 0.59105173 0.53641936 0.2978954  0.36302796 0.56022817
 0.55256059 0.34881645 0.39408932 0.59294727 0.54603456 0.34966957
 0.23577639 0.59038885 0.52721971 0.29670547 0.3451873  0.57735741
 0.49288435 0.32695931 0.25449819]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  results.loc[results.fitness_rule == fitness_rule,'Performance'] = results.loc[results.fitness_rule == fitness_rule,performance_metric]
/var/folders/z5/rq0dv5jj45qccc_tc39171cm0000gn/T/ipykernel_58323/2887299846.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.19263281 0.18664775 0.20096652 0.19289642 0.19661682 0.17761564
 0.19442911 0.19755228 0.19564214 0.19166634 0.18299811 0.17482095
 0.20208162 0.18919863 0.1076907  0.21583464 0.07390198 0.18518896
 0.01873928 0.21915752 0.00551471 0.06514573 0.27067494 0.10218254
 0.09458935 0.20988634 0.15838547 0.0800928  0.22152457 0.04387464
 0.0698734  0.21395877 0.         0.07046605 0.25600325 0.1
 0.07839351 0.17845842 0.13362425 0.11385009 0.16165928 0.
 0.07603398 0.22394599 0.10042067 0.07235512 0.17623094 0.05055147
 0.10296647 0.13012843 0.01648841 0.12773041 0.23588101 0.01650837
 0.10756357 0.22188463 0.04937755 0.08539799 0.27225208 0.04945055
 0.1169952  0.18031026 0.07824514 0.11302381 0.1631723  0.01426025
 0.09060303 0.26465511 0.05714286 0.07375941 0.25392869 0.15238095
 0.06855833 0.14339139 0.05262482 0.10162526 0.17983738 0.03803214
 0.11029739 0.21594265 0.04387464 0.09458175 0.21238761 0.13355998
 0.12944543 0.23496771 0.10218254 0.11806774 0.24894357 0.05213764
 0.07004917 0.17350555 0.01190476 0.12817972 0.20515527 0.02175742
 0.07890663 0.15151805 0.03740065 0.08916093 0.22800167 0.09285714
 0.09422782 0.21502555 0.12557513 0.17043743 0.05697608 0.21898748
 0.13643948 0.18191969 0.07822294 0.15132607 0.0093861  0.18250066
 0.01264665 0.23559673 0.17586248 0.20119128 0.12096531 0.21087333
 0.02412748 0.18387142 0.04716656 0.23445073 0.1132209  0.2090674
 0.09540628 0.1758396  0.01529371 0.18249025 0.15451562 0.12960218
 0.09163816 0.20582866 0.14099926 0.2366753  0.03453453 0.19831842
 0.11669678 0.19751087 0.04320503 0.21100369 0.11171009 0.22862629
 0.0948225  0.18915521 0.08142121 0.23568945 0.09572439 0.17217966
 0.13371856 0.18956381 0.1276793  0.19149507 0.11958928 0.20095979
 0.00578666 0.19921783 0.18474625 0.2564805  0.08839473 0.18470594
 0.06862094 0.21756002 0.20082564]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  results.loc[results.fitness_rule == fitness_rule,'Fairness'] = results.loc[results.fitness_rule == fitness_rule,fairness_metric]
/var/folders/z5/rq0dv5jj45qccc_tc39171cm0000gn/T/ipykernel_58323/2887299846.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.55988104 0.49558867 0.47660518 0.53020884 0.49731155 0.48088379
 0.50936495 0.52610501 0.50501965 0.49517103 0.52255177 0.48277552
 0.49360563 0.49928347 0.52530243 0.57125798 0.26719272 0.56423655
 0.29766735 0.36058206 0.55945517 0.29521281 0.33972048 0.55905592
 0.28944609 0.32121258 0.57663382 0.2155363  0.38625136 0.51800512
 0.56704115 0.27188547 0.41022625 0.50844818 0.58147742 0.29142379
 0.49507377 0.55088849 0.55295167 0.29014972 0.19279691 0.49465293
 0.59668217 0.27799102 0.40162431 0.50188368 0.56846199 0.26853883
 0.33775631 0.51945194 0.57722113 0.30578801 0.37184421 0.47715381
 0.57614687 0.23775601 0.21954087 0.53842681 0.55842342 0.26279497
 0.42605779 0.49253568 0.54725326 0.30749867 0.36383745 0.51679929
 0.57610948 0.25566031 0.34192284 0.51058757 0.55100198 0.30099598
 0.36266223 0.50312394 0.57982145 0.31194314 0.4653263  0.52249054
 0.56323123 0.29980176 0.33126974 0.52834554 0.54237727 0.26726369
 0.36816239 0.50039978 0.5727549  0.26481789 0.30434518 0.51789531
 0.55194807 0.32738467 0.3825255  0.54230176 0.56579268 0.30680214
 0.39278864 0.51073529 0.59522064 0.29391861 0.37328124 0.52032505
 0.56379222 0.24911704 0.27519161 0.5393946  0.58057704 0.29958191
 0.37323672 0.5309838  0.58115681 0.2283129  0.36913557 0.48187784
 0.56128043 0.2708281  0.45238095 0.53923437 0.5682019  0.29936516
 0.29872459 0.49428725 0.57227051 0.36044719 0.42488276 0.51292128
 0.58056377 0.32580119 0.38945521]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  results.loc[results.fitness_rule == fitness_rule,'Performance'] = results.loc[results.fitness_rule == fitness_rule,performance_metric]
/var/folders/z5/rq0dv5jj45qccc_tc39171cm0000gn/T/ipykernel_58323/2887299846.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.06563524 0.00434914 0.02991623 0.03287846 0.03464132 0.0015824
 0.00711975 0.00623328 0.00497483 0.00291418 0.02981982 0.0109755
 0.02228438 0.00327132 0.03014368 0.03368986 0.01061935 0.04884345
 0.00318869 0.04725275 0.07879247 0.00767757 0.12307692 0.07240013
 0.05023218 0.17032427 0.01610486 0.01464497 0.04113081 0.02539461
 0.00738464 0.03314062 0.20443238 0.01405335 0.08464225 0.04418413
 0.06341958 0.07260789 0.02708251 0.05161231 0.17274306 0.04830241
 0.01979831 0.01559766 0.03448276 0.00257988 0.0483141  0.02840623
 0.1267524  0.00821899 0.00903848 0.11110273 0.05313139 0.00603834
 0.04068929 0.0526122  0.14506428 0.04578193 0.00695801 0.04242893
 0.02784147 0.01113432 0.01962781 0.04470059 0.02865904 0.02775235
 0.01574879 0.03630877 0.14705882 0.0109844  0.10781566 0.02974926
 0.0452381  0.0050764  0.04388923 0.02444512 0.07446939 0.00696866
 0.0599006  0.04742124 0.02566656 0.01850166 0.01588528 0.00798571
 0.07470289 0.00492596 0.11916056 0.11480894 0.0967033  0.00527722
 0.10149032 0.00326027 0.11536303 0.04272904 0.01503966 0.00821274
 0.05773726 0.02078339 0.04197402 0.06509592 0.0600748  0.03245418
 0.02382688 0.07972239 0.02245123 0.0381727  0.00426904 0.03826994
 0.0041073  0.0661497  0.01623005 0.01917878 0.0258467  0.00536159
 0.02439073 0.12379038 0.03421503 0.06870452 0.00874027 0.10842825
 0.06250701 0.00047319 0.0856518  0.1045295  0.17064049 0.01275285
 0.01676805 0.09199719 0.16263736]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  results.loc[results.fitness_rule == fitness_rule,'Fairness'] = results.loc[results.fitness_rule == fitness_rule,fairness_metric]
/var/folders/z5/rq0dv5jj45qccc_tc39171cm0000gn/T/ipykernel_58323/2887299846.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.57954541 0.49072618 0.28710981 0.47937867 0.56667285 0.50660391
 0.32723168 0.35053438 0.57729636 0.54208678 0.30753588 0.36665724
 0.5817952  0.48704993 0.27473539 0.40806592 0.56092128 0.50691389
 0.28169695 0.34935224 0.58280002 0.53608789 0.28363526 0.26259378
 0.56618667 0.53844642 0.27352122 0.41388373 0.56979364 0.50332664
 0.30722702 0.28587039 0.57006344 0.56225187 0.3075192  0.25590985
 0.56668529 0.50249101 0.27698696 0.35187863 0.5788866  0.45429696
 0.32142603 0.28442427 0.57527682 0.52162962 0.30531435 0.30990314
 0.54918272 0.55022277 0.3287845  0.33054183 0.58150226 0.52734459
 0.28539259 0.32968359 0.58339716 0.50123447 0.3099627  0.310823
 0.51058757 0.55100198 0.30099598 0.36266223 0.50312394 0.57982145
 0.31194314 0.4653263  0.52249054 0.56323123 0.29980176 0.33126974
 0.52834554 0.54237727 0.26726369 0.36816239 0.50039978 0.5727549
 0.26481789 0.30434518 0.51789531 0.55194807 0.32738467 0.3825255
 0.54230176 0.56579268 0.30680214 0.39278864 0.51073529 0.59522064
 0.29391861 0.37328124 0.52032505 0.56379222 0.24911704 0.27519161
 0.5393946  0.58057704 0.29958191 0.37323672 0.5309838  0.58115681
 0.2283129  0.36913557 0.48187784 0.56128043 0.2708281  0.45238095
 0.53923437 0.5682019  0.29936516 0.29872459 0.49428725 0.57227051
 0.36044719 0.42488276 0.51292128 0.58056377 0.32580119 0.38945521]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  results.loc[results.fitness_rule == fitness_rule,'Performance'] = results.loc[results.fitness_rule == fitness_rule,performance_metric]
/var/folders/z5/rq0dv5jj45qccc_tc39171cm0000gn/T/ipykernel_58323/2887299846.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.17348809 0.0708168  0.21878785 0.05779374 0.17734029 0.13741119
 0.16846262 0.0576719  0.19223975 0.15330613 0.19948671 0.09120879
 0.14766394 0.09033556 0.22467011 0.22561649 0.16586878 0.14876613
 0.16265135 0.07191316 0.18690659 0.08392819 0.24226154 0.08909503
 0.17138109 0.01484589 0.10226686 0.02113971 0.17048347 0.07083632
 0.17467035 0.20188088 0.19338418 0.09390079 0.16006425 0.03472559
 0.16611819 0.09982902 0.21437367 0.13987373 0.19350548 0.10844246
 0.11658427 0.0703125  0.19798162 0.10315045 0.17927206 0.06925545
 0.15864095 0.11613548 0.17952911 0.16428571 0.17415626 0.0777054
 0.11085176 0.03325864 0.18485961 0.08241203 0.16908833 0.16362253
 0.0109844  0.10781566 0.02974926 0.0452381  0.0050764  0.04388923
 0.02444512 0.07446939 0.00696866 0.0599006  0.04742124 0.02566656
 0.01850166 0.01588528 0.00798571 0.07470289 0.00492596 0.11916056
 0.11480894 0.0967033  0.00527722 0.10149032 0.00326027 0.11536303
 0.04272904 0.01503966 0.00821274 0.05773726 0.02078339 0.04197402
 0.06509592 0.0600748  0.03245418 0.02382688 0.07972239 0.02245123
 0.0381727  0.00426904 0.03826994 0.0041073  0.0661497  0.01623005
 0.01917878 0.0258467  0.00536159 0.02439073 0.12379038 0.03421503
 0.06870452 0.00874027 0.10842825 0.06250701 0.00047319 0.0856518
 0.1045295  0.17064049 0.01275285 0.01676805 0.09199719 0.16263736]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  results.loc[results.fitness_rule == fitness_rule,'Fairness'] = results.loc[results.fitness_rule == fitness_rule,fairness_metric]
/var/folders/z5/rq0dv5jj45qccc_tc39171cm0000gn/T/ipykernel_58323/2887299846.py:32: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.58517004 0.58512823 0.5840247  0.5836371  0.57625737 0.5769683
 0.58075151 0.57811729 0.57147862 0.55847176 0.56402881 0.58191431
 0.58343253 0.57740222 0.51579307 0.30958237 0.37962947 0.55899189
 0.53558872 0.2598879  0.57717035 0.50086739 0.33275221 0.37929293
 0.47729109 0.29196869 0.29037704 0.52303609 0.27480633 0.38668781
 0.50626951 0.29960979 0.4042848  0.52119218 0.2936422  0.33522388
 0.49730721 0.25112662 0.35119067 0.510052   0.26843855 0.36081008
 0.52157495 0.30114722 0.42995147 0.48267704 0.29056691 0.23139881
 0.54223416 0.23653437 0.27041017 0.52121263 0.25759348 0.23912165
 0.5223892  0.27406652 0.22303564 0.54094974 0.27699558 0.30939251
 0.51731345 0.30339828 0.37825089 0.52113734 0.26323857 0.33963196
 0.5538225  0.27850228 0.30234984 0.51877126 0.29494101 0.2648939
 0.52742877 0.24492927 0.13407928 0.53530394 0.29087766 0.26820576
 0.55204731 0.29318377 0.14015216 0.51983069 0.3145689  0.47077449
 0.50770986 0.28880123 0.29866465 0.5180664  0.29093567 0.3636368
 0.53289704 0.29737768 0.38084556 0.54328387 0.28002914 0.28232519
 0.53457987 0.27840735 0.33593551 0.51796238 0.25832521 0.35528234
 0.51043886 0.30283203 0.40103589 0.56749877 0.53823804 0.31508219
 0.30011892 0.56841546 0.53593136 0.27736532 0.29276068 0.57486325
 0.55475549 0.37742341 0.41386763 0.58054526 0.52683247 0.30308226
 0.29262695 0.5799324  0.52052204 0.32271689 0.36757294 0.59460839
 0.51334273 0.35016465 0.38279532 0.56696388 0.51290233 0.36145201
 0.31417586 0.58536707 0.52205773 0.35505396 0.34556054 0.56656046
 0.50583602 0.32985378 0.33067725 0.58034596 0.53345208 0.32170125
 0.30777776 0.59105173 0.53641936 0.2978954  0.36302796 0.56022817
 0.55256059 0.34881645 0.39408932 0.59294727 0.54603456 0.34966957
 0.23577639 0.59038885 0.52721971 0.29670547 0.3451873  0.57735741
 0.49288435 0.32695931 0.25449819 0.55988104 0.49558867 0.47660518
 0.53020884 0.49731155 0.48088379 0.50936495 0.52610501 0.50501965
 0.49517103 0.52255177 0.48277552 0.49360563 0.49928347 0.52530243
 0.57125798 0.26719272 0.56423655 0.29766735 0.36058206 0.55945517
 0.29521281 0.33972048 0.55905592 0.28944609 0.32121258 0.57663382
 0.2155363  0.38625136 0.51800512 0.56704115 0.27188547 0.41022625
 0.50844818 0.58147742 0.29142379 0.49507377 0.55088849 0.55295167
 0.29014972 0.19279691 0.49465293 0.59668217 0.27799102 0.40162431
 0.50188368 0.56846199 0.26853883 0.33775631 0.51945194 0.57722113
 0.30578801 0.37184421 0.47715381 0.57614687 0.23775601 0.21954087
 0.53842681 0.55842342 0.26279497 0.42605779 0.49253568 0.54725326
 0.30749867 0.36383745 0.51679929 0.57610948 0.25566031 0.34192284
 0.51058757 0.55100198 0.30099598 0.36266223 0.50312394 0.57982145
 0.31194314 0.4653263  0.52249054 0.56323123 0.29980176 0.33126974
 0.52834554 0.54237727 0.26726369 0.36816239 0.50039978 0.5727549
 0.26481789 0.30434518 0.51789531 0.55194807 0.32738467 0.3825255
 0.54230176 0.56579268 0.30680214 0.39278864 0.51073529 0.59522064
 0.29391861 0.37328124 0.52032505 0.56379222 0.24911704 0.27519161
 0.5393946  0.58057704 0.29958191 0.37323672 0.5309838  0.58115681
 0.2283129  0.36913557 0.48187784 0.56128043 0.2708281  0.45238095
 0.53923437 0.5682019  0.29936516 0.29872459 0.49428725 0.57227051
 0.36044719 0.42488276 0.51292128 0.58056377 0.32580119 0.38945521
 0.57954541 0.49072618 0.28710981 0.47937867 0.56667285 0.50660391
 0.32723168 0.35053438 0.57729636 0.54208678 0.30753588 0.36665724
 0.5817952  0.48704993 0.27473539 0.40806592 0.56092128 0.50691389
 0.28169695 0.34935224 0.58280002 0.53608789 0.28363526 0.26259378
 0.56618667 0.53844642 0.27352122 0.41388373 0.56979364 0.50332664
 0.30722702 0.28587039 0.57006344 0.56225187 0.3075192  0.25590985
 0.56668529 0.50249101 0.27698696 0.35187863 0.5788866  0.45429696
 0.32142603 0.28442427 0.57527682 0.52162962 0.30531435 0.30990314
 0.54918272 0.55022277 0.3287845  0.33054183 0.58150226 0.52734459
 0.28539259 0.32968359 0.58339716 0.50123447 0.3099627  0.310823
 0.51058757 0.55100198 0.30099598 0.36266223 0.50312394 0.57982145
 0.31194314 0.4653263  0.52249054 0.56323123 0.29980176 0.33126974
 0.52834554 0.54237727 0.26726369 0.36816239 0.50039978 0.5727549
 0.26481789 0.30434518 0.51789531 0.55194807 0.32738467 0.3825255
 0.54230176 0.56579268 0.30680214 0.39278864 0.51073529 0.59522064
 0.29391861 0.37328124 0.52032505 0.56379222 0.24911704 0.27519161
 0.5393946  0.58057704 0.29958191 0.37323672 0.5309838  0.58115681
 0.2283129  0.36913557 0.48187784 0.56128043 0.2708281  0.45238095
 0.53923437 0.5682019  0.29936516 0.29872459 0.49428725 0.57227051
 0.36044719 0.42488276 0.51292128 0.58056377 0.32580119 0.38945521]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  results.loc[results.fitness_rule == fitness_rule,'Performance'] = results.loc[results.fitness_rule == fitness_rule,performance_metric]
/var/folders/z5/rq0dv5jj45qccc_tc39171cm0000gn/T/ipykernel_58323/2887299846.py:33: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.19263281 0.18664775 0.20096652 0.19289642 0.19661682 0.17761564
 0.19442911 0.19755228 0.19564214 0.19166634 0.18299811 0.17482095
 0.20208162 0.18919863 0.1076907  0.21583464 0.07390198 0.18518896
 0.01873928 0.21915752 0.00551471 0.06514573 0.27067494 0.10218254
 0.09458935 0.20988634 0.15838547 0.0800928  0.22152457 0.04387464
 0.0698734  0.21395877 0.         0.07046605 0.25600325 0.1
 0.07839351 0.17845842 0.13362425 0.11385009 0.16165928 0.
 0.07603398 0.22394599 0.10042067 0.07235512 0.17623094 0.05055147
 0.10296647 0.13012843 0.01648841 0.12773041 0.23588101 0.01650837
 0.10756357 0.22188463 0.04937755 0.08539799 0.27225208 0.04945055
 0.1169952  0.18031026 0.07824514 0.11302381 0.1631723  0.01426025
 0.09060303 0.26465511 0.05714286 0.07375941 0.25392869 0.15238095
 0.06855833 0.14339139 0.05262482 0.10162526 0.17983738 0.03803214
 0.11029739 0.21594265 0.04387464 0.09458175 0.21238761 0.13355998
 0.12944543 0.23496771 0.10218254 0.11806774 0.24894357 0.05213764
 0.07004917 0.17350555 0.01190476 0.12817972 0.20515527 0.02175742
 0.07890663 0.15151805 0.03740065 0.08916093 0.22800167 0.09285714
 0.09422782 0.21502555 0.12557513 0.17043743 0.05697608 0.21898748
 0.13643948 0.18191969 0.07822294 0.15132607 0.0093861  0.18250066
 0.01264665 0.23559673 0.17586248 0.20119128 0.12096531 0.21087333
 0.02412748 0.18387142 0.04716656 0.23445073 0.1132209  0.2090674
 0.09540628 0.1758396  0.01529371 0.18249025 0.15451562 0.12960218
 0.09163816 0.20582866 0.14099926 0.2366753  0.03453453 0.19831842
 0.11669678 0.19751087 0.04320503 0.21100369 0.11171009 0.22862629
 0.0948225  0.18915521 0.08142121 0.23568945 0.09572439 0.17217966
 0.13371856 0.18956381 0.1276793  0.19149507 0.11958928 0.20095979
 0.00578666 0.19921783 0.18474625 0.2564805  0.08839473 0.18470594
 0.06862094 0.21756002 0.20082564 0.06563524 0.00434914 0.02991623
 0.03287846 0.03464132 0.0015824  0.00711975 0.00623328 0.00497483
 0.00291418 0.02981982 0.0109755  0.02228438 0.00327132 0.03014368
 0.03368986 0.01061935 0.04884345 0.00318869 0.04725275 0.07879247
 0.00767757 0.12307692 0.07240013 0.05023218 0.17032427 0.01610486
 0.01464497 0.04113081 0.02539461 0.00738464 0.03314062 0.20443238
 0.01405335 0.08464225 0.04418413 0.06341958 0.07260789 0.02708251
 0.05161231 0.17274306 0.04830241 0.01979831 0.01559766 0.03448276
 0.00257988 0.0483141  0.02840623 0.1267524  0.00821899 0.00903848
 0.11110273 0.05313139 0.00603834 0.04068929 0.0526122  0.14506428
 0.04578193 0.00695801 0.04242893 0.02784147 0.01113432 0.01962781
 0.04470059 0.02865904 0.02775235 0.01574879 0.03630877 0.14705882
 0.0109844  0.10781566 0.02974926 0.0452381  0.0050764  0.04388923
 0.02444512 0.07446939 0.00696866 0.0599006  0.04742124 0.02566656
 0.01850166 0.01588528 0.00798571 0.07470289 0.00492596 0.11916056
 0.11480894 0.0967033  0.00527722 0.10149032 0.00326027 0.11536303
 0.04272904 0.01503966 0.00821274 0.05773726 0.02078339 0.04197402

In [6]:
datasets = ['Adult Income', 'Bank Marketing', 'Compas Recidivism','German Credit']
datasets

['Adult Income', 'Bank Marketing', 'Compas Recidivism', 'German Credit']

In [7]:
fitness_rules = ['mcc_parity', 'mcc_opportunity', 'mcc_odds', 'acc_parity', 'acc_opportunity', 'acc_odds']
fitness_rules

['mcc_parity',
 'mcc_opportunity',
 'mcc_odds',
 'acc_parity',
 'acc_opportunity',
 'acc_odds']

In [8]:
ftl_methods = ['FTL', r'FTL+SDR$_{\xi}$']
mlp_methods = ['MLP', r'MLP+SDR$_{\xi}$']
hifi_methods = ['HIFI', r'FTL+SDR$_{\xi}$']
significances = []
grouped_results_list = []

In [9]:
for path, methods, results in zip(['mlp_multi_aso_data_list.json', 'ftl_multi_aso_data_list.json', 'hifi_multi_aso_data_list.json'],
                                  [mlp_methods, ftl_methods, hifi_methods],
                                  (mlp_results, ftl_results, hifi_results)):
    method = methods[0]
    if os.path.exists(path):
        with open(path) as file:
            multi_aso_data_list = json.load(file)
    else:    
        multi_aso_data_list = []
        for d in datasets:
            for f in fitness_rules:
                
                baseline = results.loc[ (results['dataset'] == d) &
                                         (results['fitness_rule'] == f) &
                                         (results['method'] == methods[0]) ]\
                                .fitness.tolist()
                crp = results.loc[ (results['dataset'] == d) &
                                         (results['fitness_rule'] == f) &
                                         (results['method'] == methods[1]) ]\
                                .fitness.tolist()

                print(d, f, methods[0], methods[1])
                print(len(baseline), len(crp))

                # Teste bidirecional
                min_eps_forward = deepsig.aso(crp, baseline, confidence_level=0.95)
                min_eps_backward = deepsig.aso(baseline, crp, confidence_level=0.95)
                
                # Classificação com os thresholds especificados
                if min_eps_forward < 0.2:
                    interpretation = "significantly_better"
                    min_eps = min_eps_forward
                elif min_eps_forward < 0.5:
                    interpretation = "better"
                    min_eps = min_eps_forward
                elif min_eps_backward < 0.2:
                    interpretation = "significantly_worse"
                    min_eps = min_eps_backward
                elif min_eps_backward < 0.5:
                    interpretation = "worse"
                    min_eps = min_eps_backward
                else:
                    interpretation = "tie"
                    min_eps = min_eps_forward
                
                multi_aso_data_list.append({
                    'fitness_rule': f, 
                    'dataset': d, 
                    'min_eps': min_eps,
                    'min_eps_forward': min_eps_forward,
                    'min_eps_backward': min_eps_backward,
                    'interpretation': interpretation
                })
        with open(path, 'w') as file:
            json.dump(multi_aso_data_list, file)

    significance = pd.DataFrame(multi_aso_data_list)
    
    # Tabela de valores epsilon (forward e backward)
    eps_table_data = []
    for fitness_rule in fitness_rules:
        row_data = {'fitness_rule': fitness_rule}
        for dataset in datasets:
            subset = significance[(significance['fitness_rule'] == fitness_rule) & 
                                 (significance['dataset'] == dataset)]
            if not subset.empty:
                row = subset.iloc[0]
                row_data[f'{dataset}_forward'] = f"{row['min_eps_forward']:.3f}"
                row_data[f'{dataset}_backward'] = f"{row['min_eps_backward']:.3f}"
            else:
                row_data[f'{dataset}_forward'] = '-'
                row_data[f'{dataset}_backward'] = '-'
        eps_table_data.append(row_data)
    
    eps_df = pd.DataFrame(eps_table_data)
    eps_df.set_index('fitness_rule', inplace=True)
    
    # Criar MultiIndex columns para tabela de epsilon
    eps_columns = []
    for dataset in datasets:
        eps_columns.extend([
            (dataset, 'Forward'),
            (dataset, 'Backward')
        ])
    
    eps_df.columns = pd.MultiIndex.from_tuples(eps_columns)
    
    # Salvar tabela de epsilon
    eps_df.to_latex(f'tables/aso_epsilon_{method.lower()}_crp.tex')
    print(f'\n{method} - ASO Epsilon Values (Forward/Backward)')
    display(eps_df)
    
    # Também criar a tabela simplificada original
    pivot_df = significance.pivot_table(index='fitness_rule', columns='dataset', values='min_eps').sort_values(by='fitness_rule', ascending=False)
    pivot_df.to_latex(f'tables/aso_results_{method.lower()}_crp.tex')
    print(f'\n{method} - Summary ASO Results')
    display(pivot_df)

Adult Income mcc_parity MLP MLP+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1247.55it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1227.77it/s]

Adult Income mcc_opportunity MLP MLP+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1240.85it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1250.59it/s]

Adult Income mcc_odds MLP MLP+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1222.70it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1226.07it/s]

Adult Income acc_parity MLP MLP+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1210.77it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1240.16it/s]

Adult Income acc_opportunity MLP MLP+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1220.39it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1206.60it/s]

Adult Income acc_odds MLP MLP+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1235.90it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1221.91it/s]

Bank Marketing mcc_parity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1184.44it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1178.46it/s]

Bank Marketing mcc_opportunity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1171.48it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1195.39it/s]

Bank Marketing mcc_odds MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1171.41it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1177.19it/s]

Bank Marketing acc_parity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1176.89it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1172.95it/s]

Bank Marketing acc_opportunity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1177.43it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1162.57it/s]

Bank Marketing acc_odds MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1180.28it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1170.14it/s]

Compas Recidivism mcc_parity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1166.21it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1180.80it/s]

Compas Recidivism mcc_opportunity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1172.38it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1157.85it/s]

Compas Recidivism mcc_odds MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1168.76it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1164.58it/s]

Compas Recidivism acc_parity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1154.61it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1166.26it/s]

Compas Recidivism acc_opportunity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1166.41it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1170.69it/s]

Compas Recidivism acc_odds MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1151.32it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1150.96it/s]

German Credit mcc_parity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1169.61it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1167.06it/s]

German Credit mcc_opportunity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1164.25it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1157.38it/s]

German Credit mcc_odds MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1162.33it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1164.84it/s]

German Credit acc_parity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1156.29it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1150.55it/s]

German Credit acc_opportunity MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1166.82it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1156.22it/s]

German Credit acc_odds MLP MLP+SDR$_{\xi}$
30 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1169.76it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1148.86it/s]

MLP - ASO Epsilon Values (Forward/Backward)

                Adult Income          Bank Marketing           \
                     Forward Backward        Forward Backward
fitness_rule
mcc_parity             0.790    1.000          0.986    1.000
mcc_opportunity        0.276    1.000          1.000    0.906
mcc_odds               0.052    1.000          1.000    0.470
acc_parity             0.732    1.000          1.000    0.209
acc_opportunity        1.000    1.000          0.177    1.000
acc_odds               0.305    1.000          1.000    0.369

                Compas Recidivism          German Credit
                          Forward Backward       Forward Backward
fitness_rule
mcc_parity                  0.009    1.000         1.000    0.539
mcc_opportunity             0.004    1.000         1.000    0.743
mcc_odds                    0.198    1.000         1.000    0.628
acc_parity                  0.418    1.000         0.870    1.000
acc_opportunity             0.049    1.000         0.254    1.000
acc_odds                    0.007    1.000         0.615    1.000

MLP - Summary ASO Results

dataset,Adult Income,Bank Marketing,Compas Recidivism,German Credit
fitness_rule,,,,
mcc_parity,0.789509,0.985749,0.009040,1.000000
mcc_opportunity,0.275891,1.000000,0.003632,1.000000
mcc_odds,0.051554,0.470019,0.198298,1.000000
acc_parity,0.731755,0.208639,0.418168,0.869970
acc_opportunity,1.000000,0.176787,0.049109,0.254203
acc_odds,0.304816,0.368617,0.006884,0.614694

Adult Income mcc_parity FTL FTL+SDR$_{\xi}$
25 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1161.08it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1163.70it/s]

Adult Income mcc_opportunity FTL FTL+SDR$_{\xi}$
25 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1165.79it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1164.34it/s]

Adult Income mcc_odds FTL FTL+SDR$_{\xi}$
25 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1181.59it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1170.73it/s]

Adult Income acc_parity FTL FTL+SDR$_{\xi}$
25 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1167.20it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1169.18it/s]

Adult Income acc_opportunity FTL FTL+SDR$_{\xi}$
24 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1175.36it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1171.43it/s]

Adult Income acc_odds FTL FTL+SDR$_{\xi}$
25 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1175.53it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1178.80it/s]

Bank Marketing mcc_parity FTL FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1188.50it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1208.74it/s]

Bank Marketing mcc_opportunity FTL FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1201.62it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1205.96it/s]

Bank Marketing mcc_odds FTL FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1194.02it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1196.70it/s]

Bank Marketing acc_parity FTL FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1196.03it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1203.10it/s]

Bank Marketing acc_opportunity FTL FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1188.44it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1201.79it/s]

Bank Marketing acc_odds FTL FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1207.15it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1186.77it/s]

Compas Recidivism mcc_parity FTL FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1191.03it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1185.44it/s]

Compas Recidivism mcc_opportunity FTL FTL+SDR$_{\xi}$
14 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1200.95it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1196.31it/s]

Compas Recidivism mcc_odds FTL FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1184.81it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1189.69it/s]

Compas Recidivism acc_parity FTL FTL+SDR$_{\xi}$
14 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1192.44it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1188.72it/s]

Compas Recidivism acc_opportunity FTL FTL+SDR$_{\xi}$
14 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1192.18it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1184.35it/s]

Compas Recidivism acc_odds FTL FTL+SDR$_{\xi}$
14 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1200.14it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1201.33it/s]

German Credit mcc_parity FTL FTL+SDR$_{\xi}$
14 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1202.71it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1196.91it/s]

German Credit mcc_opportunity FTL FTL+SDR$_{\xi}$
13 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1216.68it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1201.30it/s]

German Credit mcc_odds FTL FTL+SDR$_{\xi}$
14 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1196.59it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1210.24it/s]

German Credit acc_parity FTL FTL+SDR$_{\xi}$
13 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1197.54it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1199.84it/s]

German Credit acc_opportunity FTL FTL+SDR$_{\xi}$
13 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1202.17it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1213.75it/s]

German Credit acc_odds FTL FTL+SDR$_{\xi}$
13 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1198.27it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1203.05it/s]

FTL - ASO Epsilon Values (Forward/Backward)

                Adult Income          Bank Marketing           \
                     Forward Backward        Forward Backward
fitness_rule
mcc_parity             0.316    1.000          1.000    0.468
mcc_opportunity        0.375    1.000          1.000    0.260
mcc_odds               0.317    1.000          1.000    0.973
acc_parity             0.433    1.000          1.000    0.680
acc_opportunity        0.588    1.000          0.660    1.000
acc_odds               0.438    1.000          1.000    0.450

                Compas Recidivism          German Credit
                          Forward Backward       Forward Backward
fitness_rule
mcc_parity                  1.000    0.779         0.273    1.000
mcc_opportunity             0.183    1.000         1.000    0.087
mcc_odds                    0.558    1.000         1.000    0.365
acc_parity                  0.057    1.000         1.000    0.486
acc_opportunity             1.000    0.399         1.000    0.733
acc_odds                    0.204    1.000         1.000    0.300

FTL - Summary ASO Results

dataset,Adult Income,Bank Marketing,Compas Recidivism,German Credit
fitness_rule,,,,
mcc_parity,0.316138,0.467764,1.000000,0.272724
mcc_opportunity,0.374905,0.260068,0.182578,0.086913
mcc_odds,0.317497,1.000000,0.557753,0.364560
acc_parity,0.433384,1.000000,0.057004,0.486228
acc_opportunity,0.587631,0.660108,0.398807,1.000000
acc_odds,0.438244,0.449773,0.204134,0.299867

Adult Income mcc_parity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1171.75it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1191.47it/s]

Adult Income mcc_opportunity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1184.54it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1181.19it/s]

Adult Income mcc_odds HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1173.31it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1178.96it/s]

Adult Income acc_parity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1171.47it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1175.15it/s]

Adult Income acc_opportunity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1170.49it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1173.55it/s]

Adult Income acc_odds HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1173.53it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1193.61it/s]

Bank Marketing mcc_parity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1175.26it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1164.34it/s]

Bank Marketing mcc_opportunity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1178.50it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1176.44it/s]

Bank Marketing mcc_odds HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1176.33it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1177.93it/s]

Bank Marketing acc_parity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1165.80it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1182.93it/s]

Bank Marketing acc_opportunity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1180.45it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1163.79it/s]

Bank Marketing acc_odds HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1172.43it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1170.99it/s]

Compas Recidivism mcc_parity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1170.02it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1181.42it/s]

Compas Recidivism mcc_opportunity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1167.70it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1186.06it/s]

Compas Recidivism mcc_odds HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1167.61it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1182.76it/s]

Compas Recidivism acc_parity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1164.50it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1175.09it/s]

Compas Recidivism acc_opportunity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1179.56it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1176.61it/s]

Compas Recidivism acc_odds HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1184.63it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1190.42it/s]

German Credit mcc_parity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1177.78it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1179.77it/s]

German Credit mcc_opportunity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1187.02it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1177.41it/s]

German Credit mcc_odds HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1185.82it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1172.34it/s]

German Credit acc_parity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1170.31it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1183.40it/s]

German Credit acc_opportunity HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1172.96it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1191.91it/s]

German Credit acc_odds HIFI FTL+SDR$_{\xi}$
15 15

Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1179.59it/s]
Bootstrap iterations: 100%|█████████▉| 999/1000 [00:00<00:00, 1181.53it/s]

HIFI - ASO Epsilon Values (Forward/Backward)

                Adult Income          Bank Marketing           \
                     Forward Backward        Forward Backward
fitness_rule
mcc_parity             0.000    0.997          0.000    0.998
mcc_opportunity        0.017    1.000          0.912    1.000
mcc_odds               0.022    1.000          0.027    1.000
acc_parity             0.000    0.996          1.000    0.820
acc_opportunity        0.043    1.000          1.000    0.531
acc_odds               0.018    1.000          1.000    1.000

                Compas Recidivism          German Credit
                          Forward Backward       Forward Backward
fitness_rule
mcc_parity                  0.000    0.998         0.198    1.000
mcc_opportunity             0.022    1.000         1.000    0.511
mcc_odds                    0.006    1.000         1.000    0.687
acc_parity                  0.000    1.000         1.000    0.315
acc_opportunity             0.027    1.000         0.857    1.000
acc_odds                    0.000    0.998         1.000    0.134

HIFI - Summary ASO Results

dataset,Adult Income,Bank Marketing,Compas Recidivism,German Credit
fitness_rule,,,,
mcc_parity,0.000000,0.000000,1.223873e-07,0.197881
mcc_opportunity,0.017179,0.912036,2.242494e-02,1.000000
mcc_odds,0.022113,0.026805,5.854291e-03,1.000000
acc_parity,0.000000,1.000000,0.000000e+00,0.314754
acc_opportunity,0.042555,1.000000,2.724459e-02,0.857379
acc_odds,0.018341,1.000000,5.691066e-05,0.134259

In [10]:
# Criar tabela de interpretação comparando os 3 baselines
# Carregar todos os dados ASO
all_aso_data = {}
baseline_names = ['MLP', 'FTL', 'HIFI']

# Mapeamento de interpretação para símbolos
symbol_map = {
    'significantly_better': '++',
    'better': '+',
    'tie': '≈',
    'worse': '-',
    'significantly_worse': '--'
}

for path, baseline in zip(['mlp_multi_aso_data_list.json', 'ftl_multi_aso_data_list.json', 'hifi_multi_aso_data_list.json'],
                          baseline_names):
    with open(path) as file:
        all_aso_data[baseline] = pd.DataFrame(json.load(file))

# Criar tabela de interpretação com subcolunas por dataset
interp_table_data = []
for fitness_rule in fitness_rules:
    row_data = {'fitness_rule': fitness_rule}
    for dataset in datasets:
        for baseline in baseline_names:
            subset = all_aso_data[baseline][(all_aso_data[baseline]['fitness_rule'] == fitness_rule) & 
                                            (all_aso_data[baseline]['dataset'] == dataset)]
            if not subset.empty:
                row = subset.iloc[0]
                # Converter interpretação para símbolo
                row_data[f'{dataset}_{baseline}'] = symbol_map.get(row['interpretation'], '?')
            else:
                row_data[f'{dataset}_{baseline}'] = '-'
    interp_table_data.append(row_data)

interp_df = pd.DataFrame(interp_table_data)
interp_df.set_index('fitness_rule', inplace=True)

# Criar MultiIndex columns para tabela de interpretação
interp_columns = []
for dataset in datasets:
    for baseline in baseline_names:
        interp_columns.append((dataset, baseline))

interp_df.columns = pd.MultiIndex.from_tuples(interp_columns)

# Salvar tabela de interpretação
interp_df.to_latex('tables/aso_interpretation_comparison.tex')
print('\nASO Interpretation Comparison (All Baselines)')
display(interp_df)

# Criar tabela resumo com contagem de interpretações
summary_data = []
for baseline in baseline_names:
    counts = all_aso_data[baseline]['interpretation'].value_counts()
    summary_row = {'Baseline': baseline}
    for interp_type in ['significantly_better', 'better', 'tie', 'worse', 'significantly_worse']:
        summary_row[interp_type] = counts.get(interp_type, 0)
    summary_data.append(summary_row)

summary_df = pd.DataFrame(summary_data)
summary_df.set_index('Baseline', inplace=True)

# Renomear colunas para LaTeX
summary_df.columns = ['Sig. Better (++)', 'Better (+)', 'Tie (≈)', 'Worse (-)', 'Sig. Worse (--)']

# Adicionar linha de somatório
total_row = summary_df.sum()
total_row.name = 'Total'
summary_df = pd.concat([summary_df, total_row.to_frame().T])

# Salvar tabela resumo
summary_df.to_latex('tables/aso_interpretation_summary.tex')
print('\nASO Interpretation Summary (Global Counts)')
display(summary_df)

ASO Interpretation Comparison (All Baselines)

                Adult Income          Bank Marketing           \
                         MLP FTL HIFI            MLP FTL HIFI
fitness_rule
mcc_parity                 ≈   +   ++              ≈   -   ++
mcc_opportunity            +   +   ++              ≈   -    ≈
mcc_odds                  ++   +   ++              -   ≈   ++
acc_parity                 ≈   +   ++              -   ≈    ≈
acc_opportunity            ≈   ≈   ++             ++   ≈    ≈
acc_odds                   +   +   ++              -   -    ≈

                Compas Recidivism          German Credit
                              MLP FTL HIFI           MLP FTL HIFI
fitness_rule
mcc_parity                     ++   ≈   ++             ≈   +   ++
mcc_opportunity                ++  ++   ++             ≈  --    ≈
mcc_odds                       ++   ≈   ++             ≈   -    ≈
acc_parity                      +  ++   ++             ≈   -    -
acc_opportunity                ++   -   ++             +   ≈    ≈
acc_odds                       ++   +   ++             ≈   -   --

ASO Interpretation Summary (Global Counts)

       Sig. Better (++)  Better (+)  Tie (≈)  Worse (-)  Sig. Worse (--)
MLP                   7           4       10          3                0
FTL                   2           7        7          7                1
HIFI                 15           0        7          1                1
Total                24          11       24         11                2

In [11]:
grouped_results = full_results\
    .groupby(['fitness_rule', 'dataset', 'method'])\
    .agg({'fitness': ['mean', 'std', 'count'], 'Performance': ['mean', 'std'], 'Fairness': ['mean', 'std']})\
    .sort_values(by=['fitness_rule', 'dataset', ('fitness','mean')], ascending=[False, True, False])
grouped_results['formatted_fitness'] = grouped_results.apply(lambda row: f"${row[('fitness', 'mean')]:.3f} (\pm{row[('fitness', 'std')]:.2f})$", axis=1)
grouped_results['formatted_performance'] = grouped_results.apply(lambda row: f"${row[('Performance', 'mean')]:.3f} (\pm{row[('Performance', 'std')]:.2f})$", axis=1)
grouped_results['formatted_fairness'] = grouped_results.apply(lambda row: f"${row[('Fairness', 'mean')]:.3f} (\pm{row[('Fairness', 'std')]:.2f})$", axis=1)
display(grouped_results)

                                             fitness                  \
                                                mean       std count
fitness_rule dataset       method
mcc_parity   Adult Income  FTL+SDR$_{\xi}$  0.494373  0.014363    30
                           FTL              0.486772  0.017670    25
                           HIFI             0.395732  0.014024    15
                           MLP+SDR$_{\xi}$  0.387579  0.010264    15
                           MLP              0.385655  0.010666    15
...                                              ...       ...   ...
acc_odds     German Credit HIFI             0.677358  0.042788    15
                           FTL              0.668996  0.053627    13
                           MLP+SDR$_{\xi}$  0.640351  0.062612    15
                           FTL+SDR$_{\xi}$  0.630951  0.062479    30
                           MLP              0.619366  0.070376    30

                                           Performance            Fairness  \
                                                  mean       std      mean
fitness_rule dataset       method
mcc_parity   Adult Income  FTL+SDR$_{\xi}$    0.516994  0.017254  0.022621
                           FTL                0.508716  0.021961  0.021944
                           HIFI               0.572667  0.009679  0.176935
                           MLP+SDR$_{\xi}$    0.578472  0.010924  0.190892
                           MLP                0.576385  0.009136  0.190730
...                                                ...       ...       ...
acc_odds     German Credit HIFI               0.722333  0.033587  0.044975
                           FTL                0.711923  0.019742  0.042927
                           MLP+SDR$_{\xi}$    0.747667  0.020430  0.107316
                           FTL+SDR$_{\xi}$    0.720667  0.028337  0.089716
                           MLP                0.740000  0.031786  0.120634

                                                      formatted_fitness  \
                                                 std
fitness_rule dataset       method
mcc_parity   Adult Income  FTL+SDR$_{\xi}$  0.021924  $0.494 (\pm0.01)$
                           FTL              0.019962  $0.487 (\pm0.02)$
                           HIFI             0.014412  $0.396 (\pm0.01)$
                           MLP+SDR$_{\xi}$  0.012732  $0.388 (\pm0.01)$
                           MLP              0.008002  $0.386 (\pm0.01)$
...                                              ...                ...
acc_odds     German Credit HIFI             0.044700  $0.677 (\pm0.04)$
                           FTL              0.065195  $0.669 (\pm0.05)$
                           MLP+SDR$_{\xi}$  0.058156  $0.640 (\pm0.06)$
                           FTL+SDR$_{\xi}$  0.073788  $0.631 (\pm0.06)$
                           MLP              0.068075  $0.619 (\pm0.07)$

                                           formatted_performance  \

fitness_rule dataset       method
mcc_parity   Adult Income  FTL+SDR$_{\xi}$     $0.517 (\pm0.02)$
                           FTL                 $0.509 (\pm0.02)$
                           HIFI                $0.573 (\pm0.01)$
                           MLP+SDR$_{\xi}$     $0.578 (\pm0.01)$
                           MLP                 $0.576 (\pm0.01)$
...                                                          ...
acc_odds     German Credit HIFI                $0.722 (\pm0.03)$
                           FTL                 $0.712 (\pm0.02)$
                           MLP+SDR$_{\xi}$     $0.748 (\pm0.02)$
                           FTL+SDR$_{\xi}$     $0.721 (\pm0.03)$
                           MLP                 $0.740 (\pm0.03)$

                                           formatted_fairness

fitness_rule dataset       method
mcc_parity   Adult Income  FTL+SDR$_{\xi}$  $0.023 (\pm0.02)$
                           FTL              $0.022 (\pm0.02)$
                           HIFI             $0.177 (\pm0.01)$
                           MLP+SDR$_{\xi}$  $0.191 (\pm0.01)$
                           MLP              $0.191 (\pm0.01)$
...                                                       ...
acc_odds     German Credit HIFI             $0.045 (\pm0.04)$
                           FTL              $0.043 (\pm0.07)$
                           MLP+SDR$_{\xi}$  $0.107 (\pm0.06)$
                           FTL+SDR$_{\xi}$  $0.090 (\pm0.07)$
                           MLP              $0.121 (\pm0.07)$

[120 rows x 10 columns]

In [12]:
selected_columns = ['formatted_fitness', 'formatted_performance', 'formatted_fairness']

for fitness_rule in fitness_rules:
    grouped_results.loc[fitness_rule][selected_columns].to_latex(f'tables/grouped_results_{fitness_rule}_crp.tex')
     #.to_latex(f'tables/grouped_results_{fitness_rule}_crp.tex', columns=selected_columns))